FROM node:20-slim AS builder

WORKDIR /app

COPY frontend/package.json .
RUN npm install --legacy-peer-deps

COPY frontend/ .

# skipping tsc check
RUN npx vite build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
